name: GH Release

on:
  push:
    tags:
      - "v*"

jobs:
  plugin:
    uses: hazedumper/plugin-sdk/.github/workflows/build_vs_project.yml@main
    with:
      submodules: recursive
      architecture: x64
      configuration: Release
      solution: plugin-msvc.sln
      output_file: plugin-msvc
      output_extensions: dll
      artifact_name: plugin-msvc-release

  cleanup_release:
    needs: plugin_release
    if: always()
    uses: hazedumper/plugin-sdk/.github/workflows/delete_artifacts.yml@main
    with:
      name: plugin-msvc-release
